### ISSUE TITLE
should we have this same document on english as well?

### ISSUE THREAD

**Issue by vhoyer** [quero-edu/hacktoberfest-2020#5]

**Comment by RafaelGSS** [comment]
Maybe. Not sure if the mentorship could be in English xD

**Comment by vhoyer** [comment]
we could separate a readme for english and left it open for english speaking mentors could join :thinking:, we could add our names while no one else adds theirs :sweat_smile:

**Comment by AderbalFilho** [comment]
I think we could see how it's going the accession of the one in portuguese this year and, then, think on an english for the next one. It's the first edition, so we can only see how it's going and use it to improve the next version.
